### ISSUE TITLE
Logic/Schematics files for Altium

### ISSUE THREAD

**Issue by yunusdawji** [bespoke-silicon-group/bsg_motherboards#1]
Hi,

I am trying to import the schematics for double trouble. I was able to import ASC file in altium but I cannot import the schematic. Would you be able to share the schematic file form mentor pads with us?

Thanks

**Comment by gaozihou** [comment]
Does this work for Altium import? https://github.com/bespoke-silicon-group/bsg_motherboards/blob/master/bsg_trouble/double_trouble/pcb_development/pcb_design/DaughterBoards_2016.sch

**Comment by yunusdawji** [comment]
Hi Paul,

Thanks for reply. I am trying to import it to Altium and it only accepts .txt logic file for mentor pads. Is there a different way to export logical files in Mentor graphics pads?

Yunus

**Comment by gaozihou** [comment]
Thanks Yunus! Interesting that Altium only accepts txt format..

I added the txt here: https://github.com/bespoke-silicon-group/bsg_motherboards/blob/master/bsg_trouble/double_trouble/pcb_development/pcb_design/DaughterBoards_2016.txt
