### ISSUE TITLE
Real Trouble Connector J1

### ISSUE THREAD

**Issue by abeyene** [bespoke-silicon-group/bsg_motherboards#7]
Hi @gaozihou @taylor-bsg,

I received an inquiry from Sierra today about connector J1. It seems like there are
two parts listed for it in the BOM:

i) Under description you list ASP-134488-01 (400 positions)
ii) Under Part Number and Digikey Part Number you list ASP-134604-01 (160 positions)

There are 400 pads in the gerber so I assume the first (ASP-134488-01) is the correct part. But
after looking at the [picture](https://github.com/bespoke-silicon-group/bsg_motherboards/blob/master/bsg_trouble/real_trouble/pics/real_trouble_board.jpg?raw=true) that's posted, I'm not 100% sure.

Could you clarify?

Thanks,

Abel

**Comment by gaozihou** [comment]
@abeyene,

Both ASP-134488-01 and ASP-134604-01 will function the same. The [schematic](https://github.com/bespoke-silicon-group/bsg_motherboards/blob/master/bsg_trouble/real_trouble/pcb_development/pcb_design/RealTrouble_2016_BW.pdf) shows that only LPC pins are used, all HPC pins are floating.

Normally we would install the LPC part to lower the cost. There is no harm to install the HPC one.

**Comment by abeyene** [comment]
I see. O.k. 

Thanks for the quick response.
